version: "3.8"
services:
  
  item-catalog:
    build: 
      context: ./item-catalog
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    container_name: item-catalog
    networks: 
      - mern-network
    volumes:
      - ./item-catalog/src:/usr/app/src
      - ./item-catalog/public:/usr/app/public
    depends_on:
      - server
    tty: true
    stdin_open: true
  
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    container_name: server
    networks: 
      - mern-network
    volumes:
      - ./server/src:/usr/app/src
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - mern-network
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local

networks:
  mern-network: 
    driver: local