version: "3.8"
services:
  
  frontend:
    build: 
      context: ./item-catalog
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: frontend
    volumes:
      - /usr/app
    # networks: 
    #   - mern-network
    # volumes:
      # - ./frontend/src:/usr/app/src
      # - ./frontend/public:/usr/app/public
    depends_on:
      - server
    tty: true
    stdin_open: true
  
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 4000:27017
    container_name: server
    # networks: 
    #   - mern-network
    volumes:
      - /usr/app
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    # networks:
    #   - mern-network
    volumes:
      - /usr/app

volumes:
  mongo-data:
    driver: local

networks:
  mern-network: 
    driver: bridge