version: "3.7"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
  backend:
    image: item-catalog-server:latest
    ports:
      - "4000:4000"
    networks:
      - backend-network
    volumes:
      - global-volume:/backend/backend-volume:ro
    environment:
      PORT: 4000
      MONGOURL: "mongodb+srv://donoftime2018:Godons2023!@itemsdb.ttafsh1.mongodb.net/?retryWrites=true&w=majority"
    depends_on:
      - mongodb
  frontend:
    image: item-catalog:latest
    tty: true
    stdin_open: true
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks: 
      - frontend-network
    volumes:
      - global-volume:/frontend/frontend-volume:ro
volumes:
  global-volume:
  data:

networks:
  backend-network: {}
  frontend-network : {}