version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
  server:
    build: ./server
    # image: item-catalog-server:latest
    ports:
      - "4000:4000"
    # networks:
    #   - backend-network
    volumes:
      # - global-volume:/backend/backend-volume:ro
      - logs:/app/logs
      - ./server:/app
      - /app/node_modules
    # environment:
      # PORT: 4000
      # MONGOURL: "mongodb+srv://donoftime2018:Godons2023!@itemsdb.ttafsh1.mongodb.net/?retryWrites=true&w=majority"
    depends_on:
      - mongodb
  item-catalog:
    # image: item-catalog:latest
    build: ./item-catalog
    tty: true
    stdin_open: true
    depends_on:
      - server
    ports:
      - "3000:3000"
    # networks: 
    #   - frontend-network
    volumes:
      - ./item-catalog/src:/app/src
      # - global-volume:/frontend/frontend-volume:ro
volumes:
  global-volume:
  data:
  logs:

networks:
  backend-network: {}
  frontend-network : {}