version: "3.8"
services:
  
  server:
    build: ./server
    container_name: server
    ports:
      - 4000:4000
  frontend:
    build: ./item-catalog
    container_name: frontend
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    
# volumes:
#   data-volume:
#   node_modules:
#   web-root:
#     driver: local

# networks:
#   mern-network: 
#     driver: bridge