version: "3.8"
services:
  
  frontend:
    build: 
      context: ./item-catalog
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    image: frontend-img
    container_name: frontend
    command: npm start
    volumes:
      - ./item-catalog/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server
    networks:
      - mern-network
  
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    image: backend-img
    container_name: server
    command: npm start
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    networks:
      - mern-network
  
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
    container_name: mongo-db
    networks:
      - mern-network

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local

networks:
  mern-network: 
    driver: bridge