version: '3.7'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: myapp-server
    container_name: myapp-backend-server
    command: /item-catalog/server/app/node_modules/.bin/nodemon server.js
    volumes:
      - ./server/:/item-catalog/server/app
      - /item-catalog/server/app/node_modules
    ports:
      - "4000:4000"
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-networks
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: myapp-client
    container_name: myapp-item-catalog
    command: npm start
    volumes:
      - ./client/:/item-catalog/app
      - /item-catalog/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local