version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: dockerfile
    image: item-catalog-server
    container_name: item-catalog-node-server
    command: /src/item-catalog/server/node_modules/.bin/nodemon server.js
    volumes: -

    