name: ci

on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v16

      -
        name: Install Client
        working-directory: ./item-catalog
        run: | 
            npm install
      
      -
        name: Install Server
        working-directory: ./server
        run: |
          npm install

      -
        name: Build Client Image
        working-directory: ./item-catalog
        run: |
          docker build -t donoftime2018/item-catalog:myapp-client .

      -
        name: Build Server Image
        working-directory: ./server
        run: |
          docker build -t donoftime2018/item-catalog:myapp-server .

      -
        name: Login to Docker Hub
        uses: docker/login-action@v16
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Pushing Docker Images to Docker Hub
        run: |
          docker push donoftime2018/item-catalog:myapp-client
          docker push donoftime2018/item-catalog:myapp-server